-- MySQL Script generated by MySQL Workbench
-- sáb 03 jun 2017 23:00:17 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema redesigned-couscous
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `redesigned-couscous` ;

-- -----------------------------------------------------
-- Schema redesigned-couscous
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redesigned-couscous` DEFAULT CHARACTER SET utf8 ;
USE `redesigned-couscous` ;

-- -----------------------------------------------------
-- Table `redesigned-couscous`.`aggressors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redesigned-couscous`.`aggressors` ;

CREATE TABLE IF NOT EXISTS `redesigned-couscous`.`aggressors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `victim_relationship` VARCHAR(45) NOT NULL,
  `violence_type` VARCHAR(45) NOT NULL,
  `relapse` TINYINT(4) NOT NULL,
  `work_address` VARCHAR(45) NULL DEFAULT NULL,
  `ethnicity` VARCHAR(45) NOT NULL,
  `relationship_time` VARCHAR(45) NOT NULL,
  `violence_habits` TINYINT(4) NOT NULL,
  `age` INT(11) NOT NULL,
  `enrollment` VARCHAR(45) NOT NULL,
  `comments` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `redesigned-couscous`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redesigned-couscous`.`users` ;

CREATE TABLE IF NOT EXISTS `redesigned-couscous`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `gh` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `role` INT(11) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `redesigned-couscous`.`women`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redesigned-couscous`.`women` ;

CREATE TABLE IF NOT EXISTS `redesigned-couscous`.`women` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `home_address` VARCHAR(45) NOT NULL,
  `home_reference_point` VARCHAR(45) NOT NULL,
  `home_neighborhood` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `meeting_address` VARCHAR(45) NOT NULL,
  `meeting_reference_point` VARCHAR(45) NOT NULL,
  `meeting_neighborhood` VARCHAR(45) NOT NULL,
  `best_meeting_time` VARCHAR(45) NOT NULL,
  `marital_status` VARCHAR(45) NOT NULL,
  `children_amount` INT(11) NOT NULL,
  `children_with_aggressor` INT(11) NOT NULL,
  `enrollment` VARCHAR(45) NOT NULL,
  `ethnicity` VARCHAR(45) NOT NULL,
  `age` INT(11) NOT NULL,
  `religion` VARCHAR(45) NOT NULL,
  `work` VARCHAR(45) NOT NULL,
  `last_work` VARCHAR(45) NOT NULL,
  `work_active` TINYINT(4) NOT NULL,
  `work_place` VARCHAR(45) NOT NULL,
  `income` VARCHAR(45) NOT NULL,
  `main_income_family` VARCHAR(45) NOT NULL,
  `social_government_program` VARCHAR(45) NOT NULL,
  `mpu_number` INT(11) NOT NULL,
  `request_origin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mpu_number_UNIQUE` (`mpu_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `redesigned-couscous`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `redesigned-couscous`.`visits` ;

CREATE TABLE IF NOT EXISTS `redesigned-couscous`.`visits` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `hour` TIME(1) NOT NULL,
  `occurrence_type` INT(11) NOT NULL,
  `referrals` TEXT NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `woman_comments` TEXT NULL DEFAULT NULL,
  `aggressor_comments` TEXT NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  `women_id` INT(11) NOT NULL,
  `aggressors_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `women_id`, `aggressors_id`),
  INDEX `fk_visit_users_idx` (`users_id` ASC),
  INDEX `fk_visit_women1_idx` (`women_id` ASC),
  INDEX `fk_visit_aggressor1_idx` (`aggressors_id` ASC),
  CONSTRAINT `fk_visit_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `redesigned-couscous`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_women1`
    FOREIGN KEY (`women_id`)
    REFERENCES `redesigned-couscous`.`women` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_aggressor1`
    FOREIGN KEY (`aggressors_id`)
    REFERENCES `redesigned-couscous`.`aggressors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
